name: eslint-config-typescript
on:
  push:
    branches:
      - main
    paths:
      - "eslint-config-typescript/**"
      - ".github/workflows/eslint-config-typescript.yaml"
  pull_request:
    paths:
      - "config-prettier/**"
      - ".github/workflows/config-prettier.yaml"
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@main
    secrets: inherit
    with:
      workingDirectory: "eslint-config-typescript"
      prefix: "eslint-config-typescript"
