name: eslint-config-typescript
on:
  push:
    paths:
      - 'eslint-config-typescript/**'
      - '.github/workflows/eslint-config-typescript.yaml'

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@feat/work-dir
    secrets: inherit
    with:
      workingDirectory: 'eslint-config-typescript'
      mainBranchRef: 'refs/heads/general-config-repo'