name: eslint-config-typescript
on:
  push:
    branches:
      - main
    paths:
      - "eslint-config-typescript/**"
      - ".github/workflows/eslint-config-typescript.yaml"
  pull_request:
    paths:
      - "eslint-config-typescript/**"
      - ".github/workflows/eslint-config-typescript.yaml"
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@npmjs-publish
    secrets: inherit
    with:
      workingDirectory: "eslint-config-typescript"
      prefix: "eslint-config-typescript/"
      environment: "npmjs:@openmfp/eslint-config-typescript"
