name: gha-cache
on:
  push:
    branches:
      - main
    paths:
      - "gha-cache/**"
      - ".github/workflows/gha-cache.yaml"
  pull_request:
    paths:
      - "gha-cache/**"
      - ".github/workflows/gha-cache.yaml"
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@npmjs-publish
    secrets: inherit
    with:
      workingDirectory: "gha-cache"
      publishFromDist: true
      artifactPath: "gha-cache/dist"
      workingDirectoryDist: "gha-cache/dist"
      prefix: "gha-cache/"
      environment: "npmjs:@openmfp/gha-cache"
